# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 8db49fcf18ffb95a587e4363ff42498d02c1f7ad02a1f4e8304aa48082ffe2703af2689990e5ac42cac980464bb436c67debd5ded224c8c530c3d5111d5fae02

test:
  secret_key_base: 5af7a337b0deb65073a4f8d24db9b6d674b4ca5401b766696fcbe394f19d084f4620fe2897548d43060da3594c22a8c83b63f1fc9ef092b497c4bcc23d363539

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
